module.exports = {
  SET_USER: 'SET_USER',
  AUTH_START: 'AUTH_START',
  AUTH_USER: 'AUTH_USER',
  AUTH_FAILED: 'AUTH_FAILED',
  NOTE_START_FETCH: 'NOTE_START_FETCH',
  NOTE_END_FETCH: 'NOTE_END_FETCH',
}
